name: Kernel Rebaser

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:
   
env:
  GitHubMail: ${{ secrets.GITHUBMAIL }}
  GitHubName: ${{ secrets.GITHUBNAME }}

jobs:
  debug:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email "$env:GitHubMail"
          git config --global user.name "$env:GitHubName"
          git config --global credential.helper store
          echo "https://$env:GitHubName:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
        shell: powershell
          
      - name: Rebase Kernel
        timeout-minutes: 340
        continue-on-error: true
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/$env:GitHubName/Kernel_Rebaser/main/Kernel_Updater.py" -OutFile "Kernel_Updater.py"
          python3 Kernel_Updater.py
        shell: powershell